[package]
name = "nf_simulator"
version = "0.1.0"
authors = ["jack"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lkl = { path = "../rust-lkl" }
libc = "*"
errno = "0.2.5"
paste = "0.1"